CREATE TABLE customers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(50) NOT NULL,
    age integer NOT NULL,
    salary integer NOT NULL,
    address VARCHAR2(120),
    PRIMARY KEY(id)
);