package com.paras.model;

public class TAttributeconstraints {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attributeconstraints.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer object_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attributeconstraints.Constraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String constraint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attributeconstraints.AttName
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String attName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attributeconstraints.Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attributeconstraints.ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attributeconstraints.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attributeconstraints.Object_ID
     *
     * @return the value of t_attributeconstraints.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getObject_ID() {
        return object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attributeconstraints.Object_ID
     *
     * @param object_ID the value for t_attributeconstraints.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setObject_ID(Integer object_ID) {
        this.object_ID = object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attributeconstraints.Constraint
     *
     * @return the value of t_attributeconstraints.Constraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getConstraint() {
        return constraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attributeconstraints.Constraint
     *
     * @param constraint the value for t_attributeconstraints.Constraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setConstraint(String constraint) {
        this.constraint = constraint == null ? null : constraint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attributeconstraints.AttName
     *
     * @return the value of t_attributeconstraints.AttName
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getAttName() {
        return attName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attributeconstraints.AttName
     *
     * @param attName the value for t_attributeconstraints.AttName
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setAttName(String attName) {
        this.attName = attName == null ? null : attName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attributeconstraints.Type
     *
     * @return the value of t_attributeconstraints.Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attributeconstraints.Type
     *
     * @param type the value for t_attributeconstraints.Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attributeconstraints.ID
     *
     * @return the value of t_attributeconstraints.ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attributeconstraints.ID
     *
     * @param ID the value for t_attributeconstraints.ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attributeconstraints.Notes
     *
     * @return the value of t_attributeconstraints.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attributeconstraints.Notes
     *
     * @param notes the value for t_attributeconstraints.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
        if(this.notes != null) {
            this.notes.replace("'", "\'"); // escape quote
            this.notes.replace("", "\""); // escape quote
        }
    }
}