package com.paras.model;

import java.util.UUID;

public class TConnector {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Connector_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer connector_ID;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Direction
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String direction;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Connector_Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String connector_Type;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SubType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String subType;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceCard
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String sourceCard;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceAccess
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String sourceAccess;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceElement
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String sourceElement;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestCard
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String destCard;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestAccess
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String destAccess;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestElement
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String destElement;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceRole
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String sourceRole;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceRoleType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String sourceRoleType;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceContainment
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String sourceContainment;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceIsAggregate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer sourceIsAggregate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceIsOrdered
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer sourceIsOrdered;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceQualifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String sourceQualifier;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestRole
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String destRole;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestRoleType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String destRoleType;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestContainment
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String destContainment;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestIsAggregate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer destIsAggregate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestIsOrdered
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer destIsOrdered;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestQualifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String destQualifier;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Start_Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer start_Object_ID;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.End_Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer end_Object_ID;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Top_Start_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String top_Start_Label;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Top_Mid_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String top_Mid_Label;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Top_End_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String top_End_Label;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Btm_Start_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String btm_Start_Label;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Btm_Mid_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String btm_Mid_Label;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Btm_End_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String btm_End_Label;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Start_Edge
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer start_Edge;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.End_Edge
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer end_Edge;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.PtStartX
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer ptStartX;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.PtStartY
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer ptStartY;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.PtEndX
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer ptEndX;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.PtEndY
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer ptEndY;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SeqNo
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer seqNo;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.HeadStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer headStyle;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.LineStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer lineStyle;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.RouteStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer routeStyle;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.IsBold
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer isBold;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.LineColor
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer lineColor;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Stereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String stereotype;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.VirtualInheritance
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String virtualInheritance;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.LinkAccess
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String linkAccess;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.PDATA1
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String PDATA1;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.PDATA2
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String PDATA2;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.PDATA3
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String PDATA3;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.PDATA4
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String PDATA4;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.PDATA5
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String PDATA5;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DiagramID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer diagramID;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String ea_guid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceConstraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String sourceConstraint;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestConstraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String destConstraint;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceIsNavigable
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean sourceIsNavigable;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestIsNavigable
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean destIsNavigable;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.IsRoot
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean isRoot;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.IsLeaf
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean isLeaf;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.IsSpec
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean isSpec;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceChangeable
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String sourceChangeable;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestChangeable
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String destChangeable;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceTS
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String sourceTS;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestTS
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String destTS;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.StateFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String stateFlags;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.ActionFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String actionFlags;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.IsSignal
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean isSignal;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.IsStimulus
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean isStimulus;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DispatchAction
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String dispatchAction;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Target2
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer target2;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceStereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String sourceStereotype;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestStereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String destStereotype;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.EventFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String eventFlags;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestRoleNote
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String destRoleNote;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.DestStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String destStyle;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String notes;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceRoleNote
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String sourceRoleNote;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.SourceStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String sourceStyle;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connector.StyleEx
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String styleEx;

    public TConnector() {
        this(false);
    }

    public TConnector(boolean init) {
        if (init) {
            initGuid();
        }
    }

    public void initGuid() {
        setEa_guid("{" + UUID.randomUUID() + "}");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Connector_ID
     *
     * @return the value of t_connector.Connector_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getConnector_ID() {
        return connector_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Connector_ID
     *
     * @param connector_ID the value for t_connector.Connector_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setConnector_ID(Integer connector_ID) {
        this.connector_ID = connector_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Name
     *
     * @return the value of t_connector.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Name
     *
     * @param name the value for t_connector.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Direction
     *
     * @return the value of t_connector.Direction
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Direction
     *
     * @param direction the value for t_connector.Direction
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Connector_Type
     *
     * @return the value of t_connector.Connector_Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getConnector_Type() {
        return connector_Type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Connector_Type
     *
     * @param connector_Type the value for t_connector.Connector_Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setConnector_Type(String connector_Type) {
        this.connector_Type = connector_Type == null ? null : connector_Type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SubType
     *
     * @return the value of t_connector.SubType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSubType() {
        return subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SubType
     *
     * @param subType the value for t_connector.SubType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSubType(String subType) {
        this.subType = subType == null ? null : subType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceCard
     *
     * @return the value of t_connector.SourceCard
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSourceCard() {
        return sourceCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceCard
     *
     * @param sourceCard the value for t_connector.SourceCard
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceCard(String sourceCard) {
        this.sourceCard = sourceCard == null ? null : sourceCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceAccess
     *
     * @return the value of t_connector.SourceAccess
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSourceAccess() {
        return sourceAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceAccess
     *
     * @param sourceAccess the value for t_connector.SourceAccess
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceAccess(String sourceAccess) {
        this.sourceAccess = sourceAccess == null ? null : sourceAccess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceElement
     *
     * @return the value of t_connector.SourceElement
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSourceElement() {
        return sourceElement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceElement
     *
     * @param sourceElement the value for t_connector.SourceElement
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceElement(String sourceElement) {
        this.sourceElement = sourceElement == null ? null : sourceElement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestCard
     *
     * @return the value of t_connector.DestCard
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDestCard() {
        return destCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestCard
     *
     * @param destCard the value for t_connector.DestCard
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestCard(String destCard) {
        this.destCard = destCard == null ? null : destCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestAccess
     *
     * @return the value of t_connector.DestAccess
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDestAccess() {
        return destAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestAccess
     *
     * @param destAccess the value for t_connector.DestAccess
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestAccess(String destAccess) {
        this.destAccess = destAccess == null ? null : destAccess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestElement
     *
     * @return the value of t_connector.DestElement
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDestElement() {
        return destElement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestElement
     *
     * @param destElement the value for t_connector.DestElement
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestElement(String destElement) {
        this.destElement = destElement == null ? null : destElement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceRole
     *
     * @return the value of t_connector.SourceRole
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSourceRole() {
        return sourceRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceRole
     *
     * @param sourceRole the value for t_connector.SourceRole
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceRole(String sourceRole) {
        this.sourceRole = sourceRole == null ? null : sourceRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceRoleType
     *
     * @return the value of t_connector.SourceRoleType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSourceRoleType() {
        return sourceRoleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceRoleType
     *
     * @param sourceRoleType the value for t_connector.SourceRoleType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceRoleType(String sourceRoleType) {
        this.sourceRoleType = sourceRoleType == null ? null : sourceRoleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceContainment
     *
     * @return the value of t_connector.SourceContainment
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSourceContainment() {
        return sourceContainment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceContainment
     *
     * @param sourceContainment the value for t_connector.SourceContainment
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceContainment(String sourceContainment) {
        this.sourceContainment = sourceContainment == null ? null : sourceContainment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceIsAggregate
     *
     * @return the value of t_connector.SourceIsAggregate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getSourceIsAggregate() {
        return sourceIsAggregate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceIsAggregate
     *
     * @param sourceIsAggregate the value for t_connector.SourceIsAggregate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceIsAggregate(Integer sourceIsAggregate) {
        this.sourceIsAggregate = sourceIsAggregate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceIsOrdered
     *
     * @return the value of t_connector.SourceIsOrdered
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getSourceIsOrdered() {
        return sourceIsOrdered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceIsOrdered
     *
     * @param sourceIsOrdered the value for t_connector.SourceIsOrdered
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceIsOrdered(Integer sourceIsOrdered) {
        this.sourceIsOrdered = sourceIsOrdered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceQualifier
     *
     * @return the value of t_connector.SourceQualifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSourceQualifier() {
        return sourceQualifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceQualifier
     *
     * @param sourceQualifier the value for t_connector.SourceQualifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceQualifier(String sourceQualifier) {
        this.sourceQualifier = sourceQualifier == null ? null : sourceQualifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestRole
     *
     * @return the value of t_connector.DestRole
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDestRole() {
        return destRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestRole
     *
     * @param destRole the value for t_connector.DestRole
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestRole(String destRole) {
        this.destRole = destRole == null ? null : destRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestRoleType
     *
     * @return the value of t_connector.DestRoleType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDestRoleType() {
        return destRoleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestRoleType
     *
     * @param destRoleType the value for t_connector.DestRoleType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestRoleType(String destRoleType) {
        this.destRoleType = destRoleType == null ? null : destRoleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestContainment
     *
     * @return the value of t_connector.DestContainment
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDestContainment() {
        return destContainment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestContainment
     *
     * @param destContainment the value for t_connector.DestContainment
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestContainment(String destContainment) {
        this.destContainment = destContainment == null ? null : destContainment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestIsAggregate
     *
     * @return the value of t_connector.DestIsAggregate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getDestIsAggregate() {
        return destIsAggregate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestIsAggregate
     *
     * @param destIsAggregate the value for t_connector.DestIsAggregate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestIsAggregate(Integer destIsAggregate) {
        this.destIsAggregate = destIsAggregate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestIsOrdered
     *
     * @return the value of t_connector.DestIsOrdered
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getDestIsOrdered() {
        return destIsOrdered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestIsOrdered
     *
     * @param destIsOrdered the value for t_connector.DestIsOrdered
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestIsOrdered(Integer destIsOrdered) {
        this.destIsOrdered = destIsOrdered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestQualifier
     *
     * @return the value of t_connector.DestQualifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDestQualifier() {
        return destQualifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestQualifier
     *
     * @param destQualifier the value for t_connector.DestQualifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestQualifier(String destQualifier) {
        this.destQualifier = destQualifier == null ? null : destQualifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Start_Object_ID
     *
     * @return the value of t_connector.Start_Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getStart_Object_ID() {
        return start_Object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Start_Object_ID
     *
     * @param start_Object_ID the value for t_connector.Start_Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStart_Object_ID(Integer start_Object_ID) {
        this.start_Object_ID = start_Object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.End_Object_ID
     *
     * @return the value of t_connector.End_Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getEnd_Object_ID() {
        return end_Object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.End_Object_ID
     *
     * @param end_Object_ID the value for t_connector.End_Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setEnd_Object_ID(Integer end_Object_ID) {
        this.end_Object_ID = end_Object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Top_Start_Label
     *
     * @return the value of t_connector.Top_Start_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getTop_Start_Label() {
        return top_Start_Label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Top_Start_Label
     *
     * @param top_Start_Label the value for t_connector.Top_Start_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setTop_Start_Label(String top_Start_Label) {
        this.top_Start_Label = top_Start_Label == null ? null : top_Start_Label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Top_Mid_Label
     *
     * @return the value of t_connector.Top_Mid_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getTop_Mid_Label() {
        return top_Mid_Label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Top_Mid_Label
     *
     * @param top_Mid_Label the value for t_connector.Top_Mid_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setTop_Mid_Label(String top_Mid_Label) {
        this.top_Mid_Label = top_Mid_Label == null ? null : top_Mid_Label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Top_End_Label
     *
     * @return the value of t_connector.Top_End_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getTop_End_Label() {
        return top_End_Label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Top_End_Label
     *
     * @param top_End_Label the value for t_connector.Top_End_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setTop_End_Label(String top_End_Label) {
        this.top_End_Label = top_End_Label == null ? null : top_End_Label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Btm_Start_Label
     *
     * @return the value of t_connector.Btm_Start_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getBtm_Start_Label() {
        return btm_Start_Label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Btm_Start_Label
     *
     * @param btm_Start_Label the value for t_connector.Btm_Start_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setBtm_Start_Label(String btm_Start_Label) {
        this.btm_Start_Label = btm_Start_Label == null ? null : btm_Start_Label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Btm_Mid_Label
     *
     * @return the value of t_connector.Btm_Mid_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getBtm_Mid_Label() {
        return btm_Mid_Label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Btm_Mid_Label
     *
     * @param btm_Mid_Label the value for t_connector.Btm_Mid_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setBtm_Mid_Label(String btm_Mid_Label) {
        this.btm_Mid_Label = btm_Mid_Label == null ? null : btm_Mid_Label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Btm_End_Label
     *
     * @return the value of t_connector.Btm_End_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getBtm_End_Label() {
        return btm_End_Label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Btm_End_Label
     *
     * @param btm_End_Label the value for t_connector.Btm_End_Label
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setBtm_End_Label(String btm_End_Label) {
        this.btm_End_Label = btm_End_Label == null ? null : btm_End_Label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Start_Edge
     *
     * @return the value of t_connector.Start_Edge
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getStart_Edge() {
        return start_Edge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Start_Edge
     *
     * @param start_Edge the value for t_connector.Start_Edge
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStart_Edge(Integer start_Edge) {
        this.start_Edge = start_Edge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.End_Edge
     *
     * @return the value of t_connector.End_Edge
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getEnd_Edge() {
        return end_Edge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.End_Edge
     *
     * @param end_Edge the value for t_connector.End_Edge
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setEnd_Edge(Integer end_Edge) {
        this.end_Edge = end_Edge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.PtStartX
     *
     * @return the value of t_connector.PtStartX
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getPtStartX() {
        return ptStartX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.PtStartX
     *
     * @param ptStartX the value for t_connector.PtStartX
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPtStartX(Integer ptStartX) {
        this.ptStartX = ptStartX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.PtStartY
     *
     * @return the value of t_connector.PtStartY
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getPtStartY() {
        return ptStartY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.PtStartY
     *
     * @param ptStartY the value for t_connector.PtStartY
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPtStartY(Integer ptStartY) {
        this.ptStartY = ptStartY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.PtEndX
     *
     * @return the value of t_connector.PtEndX
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getPtEndX() {
        return ptEndX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.PtEndX
     *
     * @param ptEndX the value for t_connector.PtEndX
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPtEndX(Integer ptEndX) {
        this.ptEndX = ptEndX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.PtEndY
     *
     * @return the value of t_connector.PtEndY
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getPtEndY() {
        return ptEndY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.PtEndY
     *
     * @param ptEndY the value for t_connector.PtEndY
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPtEndY(Integer ptEndY) {
        this.ptEndY = ptEndY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SeqNo
     *
     * @return the value of t_connector.SeqNo
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SeqNo
     *
     * @param seqNo the value for t_connector.SeqNo
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.HeadStyle
     *
     * @return the value of t_connector.HeadStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getHeadStyle() {
        return headStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.HeadStyle
     *
     * @param headStyle the value for t_connector.HeadStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setHeadStyle(Integer headStyle) {
        this.headStyle = headStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.LineStyle
     *
     * @return the value of t_connector.LineStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getLineStyle() {
        return lineStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.LineStyle
     *
     * @param lineStyle the value for t_connector.LineStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setLineStyle(Integer lineStyle) {
        this.lineStyle = lineStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.RouteStyle
     *
     * @return the value of t_connector.RouteStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getRouteStyle() {
        return routeStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.RouteStyle
     *
     * @param routeStyle the value for t_connector.RouteStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setRouteStyle(Integer routeStyle) {
        this.routeStyle = routeStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.IsBold
     *
     * @return the value of t_connector.IsBold
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getIsBold() {
        return isBold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.IsBold
     *
     * @param isBold the value for t_connector.IsBold
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsBold(Integer isBold) {
        this.isBold = isBold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.LineColor
     *
     * @return the value of t_connector.LineColor
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getLineColor() {
        return lineColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.LineColor
     *
     * @param lineColor the value for t_connector.LineColor
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setLineColor(Integer lineColor) {
        this.lineColor = lineColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Stereotype
     *
     * @return the value of t_connector.Stereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getStereotype() {
        return stereotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Stereotype
     *
     * @param stereotype the value for t_connector.Stereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStereotype(String stereotype) {
        this.stereotype = stereotype == null ? null : stereotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.VirtualInheritance
     *
     * @return the value of t_connector.VirtualInheritance
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getVirtualInheritance() {
        return virtualInheritance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.VirtualInheritance
     *
     * @param virtualInheritance the value for t_connector.VirtualInheritance
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setVirtualInheritance(String virtualInheritance) {
        this.virtualInheritance = virtualInheritance == null ? null : virtualInheritance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.LinkAccess
     *
     * @return the value of t_connector.LinkAccess
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getLinkAccess() {
        return linkAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.LinkAccess
     *
     * @param linkAccess the value for t_connector.LinkAccess
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setLinkAccess(String linkAccess) {
        this.linkAccess = linkAccess == null ? null : linkAccess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.PDATA1
     *
     * @return the value of t_connector.PDATA1
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPDATA1() {
        return PDATA1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.PDATA1
     *
     * @param PDATA1 the value for t_connector.PDATA1
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPDATA1(String PDATA1) {
        this.PDATA1 = PDATA1 == null ? null : PDATA1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.PDATA2
     *
     * @return the value of t_connector.PDATA2
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPDATA2() {
        return PDATA2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.PDATA2
     *
     * @param PDATA2 the value for t_connector.PDATA2
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPDATA2(String PDATA2) {
        this.PDATA2 = PDATA2 == null ? null : PDATA2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.PDATA3
     *
     * @return the value of t_connector.PDATA3
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPDATA3() {
        return PDATA3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.PDATA3
     *
     * @param PDATA3 the value for t_connector.PDATA3
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPDATA3(String PDATA3) {
        this.PDATA3 = PDATA3 == null ? null : PDATA3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.PDATA4
     *
     * @return the value of t_connector.PDATA4
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPDATA4() {
        return PDATA4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.PDATA4
     *
     * @param PDATA4 the value for t_connector.PDATA4
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPDATA4(String PDATA4) {
        this.PDATA4 = PDATA4 == null ? null : PDATA4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.PDATA5
     *
     * @return the value of t_connector.PDATA5
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPDATA5() {
        return PDATA5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.PDATA5
     *
     * @param PDATA5 the value for t_connector.PDATA5
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPDATA5(String PDATA5) {
        this.PDATA5 = PDATA5 == null ? null : PDATA5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DiagramID
     *
     * @return the value of t_connector.DiagramID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getDiagramID() {
        return diagramID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DiagramID
     *
     * @param diagramID the value for t_connector.DiagramID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDiagramID(Integer diagramID) {
        this.diagramID = diagramID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.ea_guid
     *
     * @return the value of t_connector.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getEa_guid() {
        return ea_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.ea_guid
     *
     * @param ea_guid the value for t_connector.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setEa_guid(String ea_guid) {
        this.ea_guid = ea_guid == null ? null : ea_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceConstraint
     *
     * @return the value of t_connector.SourceConstraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSourceConstraint() {
        return sourceConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceConstraint
     *
     * @param sourceConstraint the value for t_connector.SourceConstraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceConstraint(String sourceConstraint) {
        this.sourceConstraint = sourceConstraint == null ? null : sourceConstraint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestConstraint
     *
     * @return the value of t_connector.DestConstraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDestConstraint() {
        return destConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestConstraint
     *
     * @param destConstraint the value for t_connector.DestConstraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestConstraint(String destConstraint) {
        this.destConstraint = destConstraint == null ? null : destConstraint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceIsNavigable
     *
     * @return the value of t_connector.SourceIsNavigable
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getSourceIsNavigable() {
        return sourceIsNavigable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceIsNavigable
     *
     * @param sourceIsNavigable the value for t_connector.SourceIsNavigable
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceIsNavigable(Boolean sourceIsNavigable) {
        this.sourceIsNavigable = sourceIsNavigable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestIsNavigable
     *
     * @return the value of t_connector.DestIsNavigable
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getDestIsNavigable() {
        return destIsNavigable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestIsNavigable
     *
     * @param destIsNavigable the value for t_connector.DestIsNavigable
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestIsNavigable(Boolean destIsNavigable) {
        this.destIsNavigable = destIsNavigable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.IsRoot
     *
     * @return the value of t_connector.IsRoot
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getIsRoot() {
        return isRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.IsRoot
     *
     * @param isRoot the value for t_connector.IsRoot
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsRoot(Boolean isRoot) {
        this.isRoot = isRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.IsLeaf
     *
     * @return the value of t_connector.IsLeaf
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.IsLeaf
     *
     * @param isLeaf the value for t_connector.IsLeaf
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsLeaf(Boolean isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.IsSpec
     *
     * @return the value of t_connector.IsSpec
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getIsSpec() {
        return isSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.IsSpec
     *
     * @param isSpec the value for t_connector.IsSpec
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsSpec(Boolean isSpec) {
        this.isSpec = isSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceChangeable
     *
     * @return the value of t_connector.SourceChangeable
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSourceChangeable() {
        return sourceChangeable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceChangeable
     *
     * @param sourceChangeable the value for t_connector.SourceChangeable
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceChangeable(String sourceChangeable) {
        this.sourceChangeable = sourceChangeable == null ? null : sourceChangeable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestChangeable
     *
     * @return the value of t_connector.DestChangeable
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDestChangeable() {
        return destChangeable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestChangeable
     *
     * @param destChangeable the value for t_connector.DestChangeable
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestChangeable(String destChangeable) {
        this.destChangeable = destChangeable == null ? null : destChangeable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceTS
     *
     * @return the value of t_connector.SourceTS
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSourceTS() {
        return sourceTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceTS
     *
     * @param sourceTS the value for t_connector.SourceTS
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceTS(String sourceTS) {
        this.sourceTS = sourceTS == null ? null : sourceTS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestTS
     *
     * @return the value of t_connector.DestTS
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDestTS() {
        return destTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestTS
     *
     * @param destTS the value for t_connector.DestTS
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestTS(String destTS) {
        this.destTS = destTS == null ? null : destTS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.StateFlags
     *
     * @return the value of t_connector.StateFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getStateFlags() {
        return stateFlags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.StateFlags
     *
     * @param stateFlags the value for t_connector.StateFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStateFlags(String stateFlags) {
        this.stateFlags = stateFlags == null ? null : stateFlags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.ActionFlags
     *
     * @return the value of t_connector.ActionFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getActionFlags() {
        return actionFlags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.ActionFlags
     *
     * @param actionFlags the value for t_connector.ActionFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setActionFlags(String actionFlags) {
        this.actionFlags = actionFlags == null ? null : actionFlags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.IsSignal
     *
     * @return the value of t_connector.IsSignal
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getIsSignal() {
        return isSignal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.IsSignal
     *
     * @param isSignal the value for t_connector.IsSignal
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsSignal(Boolean isSignal) {
        this.isSignal = isSignal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.IsStimulus
     *
     * @return the value of t_connector.IsStimulus
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getIsStimulus() {
        return isStimulus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.IsStimulus
     *
     * @param isStimulus the value for t_connector.IsStimulus
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsStimulus(Boolean isStimulus) {
        this.isStimulus = isStimulus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DispatchAction
     *
     * @return the value of t_connector.DispatchAction
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDispatchAction() {
        return dispatchAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DispatchAction
     *
     * @param dispatchAction the value for t_connector.DispatchAction
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDispatchAction(String dispatchAction) {
        this.dispatchAction = dispatchAction == null ? null : dispatchAction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Target2
     *
     * @return the value of t_connector.Target2
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getTarget2() {
        return target2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Target2
     *
     * @param target2 the value for t_connector.Target2
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setTarget2(Integer target2) {
        this.target2 = target2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceStereotype
     *
     * @return the value of t_connector.SourceStereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSourceStereotype() {
        return sourceStereotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceStereotype
     *
     * @param sourceStereotype the value for t_connector.SourceStereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceStereotype(String sourceStereotype) {
        this.sourceStereotype = sourceStereotype == null ? null : sourceStereotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestStereotype
     *
     * @return the value of t_connector.DestStereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDestStereotype() {
        return destStereotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestStereotype
     *
     * @param destStereotype the value for t_connector.DestStereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestStereotype(String destStereotype) {
        this.destStereotype = destStereotype == null ? null : destStereotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.EventFlags
     *
     * @return the value of t_connector.EventFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getEventFlags() {
        return eventFlags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.EventFlags
     *
     * @param eventFlags the value for t_connector.EventFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setEventFlags(String eventFlags) {
        this.eventFlags = eventFlags == null ? null : eventFlags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestRoleNote
     *
     * @return the value of t_connector.DestRoleNote
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDestRoleNote() {
        return destRoleNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.DestStyle
     *
     * @return the value of t_connector.DestStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDestStyle() {
        return destStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.Notes
     *
     * @return the value of t_connector.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceRoleNote
     *
     * @return the value of t_connector.SourceRoleNote
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSourceRoleNote() {
        return sourceRoleNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.SourceStyle
     *
     * @return the value of t_connector.SourceStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSourceStyle() {
        return sourceStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connector.StyleEx
     *
     * @return the value of t_connector.StyleEx
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getStyleEx() {
        return styleEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestRoleNote
     *
     * @param destRoleNote the value for t_connector.DestRoleNote
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestRoleNote(String destRoleNote) {
        this.destRoleNote = destRoleNote == null ? null : destRoleNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.DestStyle
     *
     * @param destStyle the value for t_connector.DestStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDestStyle(String destStyle) {
        this.destStyle = destStyle == null ? null : destStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.Notes
     *
     * @param notes the value for t_connector.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
        if(this.notes != null) {
            this.notes.replace("'", "\'"); // escape quote
            this.notes.replace("", "\""); // escape quote
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceRoleNote
     *
     * @param sourceRoleNote the value for t_connector.SourceRoleNote
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceRoleNote(String sourceRoleNote) {
        this.sourceRoleNote = sourceRoleNote == null ? null : sourceRoleNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.SourceStyle
     *
     * @param sourceStyle the value for t_connector.SourceStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSourceStyle(String sourceStyle) {
        this.sourceStyle = sourceStyle == null ? null : sourceStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connector.StyleEx
     *
     * @param styleEx the value for t_connector.StyleEx
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStyleEx(String styleEx) {
        this.styleEx = styleEx == null ? null : styleEx.trim();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TConnector other = (TConnector) obj;
        if ((this.ea_guid == null) ? (other.ea_guid != null) : !this.ea_guid.equals(other.ea_guid)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 13 * hash + (this.ea_guid != null ? this.ea_guid.hashCode() : 0);
        return hash;
    }
}