package com.paras.model;

public class TConnectorconstraint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connectorconstraint.ConnectorID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer connectorID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connectorconstraint.Constraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String constraint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connectorconstraint.ConstraintType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String constraintType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_connectorconstraint.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connectorconstraint.ConnectorID
     *
     * @return the value of t_connectorconstraint.ConnectorID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getConnectorID() {
        return connectorID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connectorconstraint.ConnectorID
     *
     * @param connectorID the value for t_connectorconstraint.ConnectorID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setConnectorID(Integer connectorID) {
        this.connectorID = connectorID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connectorconstraint.Constraint
     *
     * @return the value of t_connectorconstraint.Constraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getConstraint() {
        return constraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connectorconstraint.Constraint
     *
     * @param constraint the value for t_connectorconstraint.Constraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setConstraint(String constraint) {
        this.constraint = constraint == null ? null : constraint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connectorconstraint.ConstraintType
     *
     * @return the value of t_connectorconstraint.ConstraintType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getConstraintType() {
        return constraintType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connectorconstraint.ConstraintType
     *
     * @param constraintType the value for t_connectorconstraint.ConstraintType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setConstraintType(String constraintType) {
        this.constraintType = constraintType == null ? null : constraintType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_connectorconstraint.Notes
     *
     * @return the value of t_connectorconstraint.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_connectorconstraint.Notes
     *
     * @param notes the value for t_connectorconstraint.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
        if(this.notes != null) {
            this.notes.replace("'", "\'"); // escape quote
            this.notes.replace("", "\""); // escape quote        
        }
    }
}