package com.paras.model;

public class TMethod {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_method.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer object_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_method.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_method.Scope
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_method.Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_method.Object_ID
     *
     * @return the value of t_method.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getObject_ID() {
        return object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_method.Object_ID
     *
     * @param object_ID the value for t_method.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setObject_ID(Integer object_ID) {
        this.object_ID = object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_method.Name
     *
     * @return the value of t_method.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_method.Name
     *
     * @param name the value for t_method.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_method.Scope
     *
     * @return the value of t_method.Scope
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_method.Scope
     *
     * @param scope the value for t_method.Scope
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_method.Type
     *
     * @return the value of t_method.Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_method.Type
     *
     * @param type the value for t_method.Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}