package com.paras.model;

import java.util.UUID;

public class TObjectproperties {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_objectproperties.PropertyID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer propertyID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_objectproperties.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer object_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_objectproperties.Property
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_objectproperties.Value
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_objectproperties.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String ea_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_objectproperties.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String notes;
    
    public TObjectproperties() {
        this(false);
    }
    
    public TObjectproperties(boolean init) {
        if(init) {
            initGuid();
        }
    }
    
    public void initGuid() {
        setEa_guid("{" + UUID.randomUUID() + "}");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_objectproperties.PropertyID
     *
     * @return the value of t_objectproperties.PropertyID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getPropertyID() {
        return propertyID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_objectproperties.PropertyID
     *
     * @param propertyID the value for t_objectproperties.PropertyID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPropertyID(Integer propertyID) {
        this.propertyID = propertyID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_objectproperties.Object_ID
     *
     * @return the value of t_objectproperties.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getObject_ID() {
        return object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_objectproperties.Object_ID
     *
     * @param object_ID the value for t_objectproperties.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setObject_ID(Integer object_ID) {
        this.object_ID = object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_objectproperties.Property
     *
     * @return the value of t_objectproperties.Property
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_objectproperties.Property
     *
     * @param property the value for t_objectproperties.Property
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_objectproperties.Value
     *
     * @return the value of t_objectproperties.Value
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_objectproperties.Value
     *
     * @param value the value for t_objectproperties.Value
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_objectproperties.ea_guid
     *
     * @return the value of t_objectproperties.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getEa_guid() {
        return ea_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_objectproperties.ea_guid
     *
     * @param ea_guid the value for t_objectproperties.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setEa_guid(String ea_guid) {
        this.ea_guid = ea_guid == null ? null : ea_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_objectproperties.Notes
     *
     * @return the value of t_objectproperties.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_objectproperties.Notes
     *
     * @param notes the value for t_objectproperties.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
        if(this.notes != null) {
            this.notes.replace("'", "\'"); // escape quote
            this.notes.replace("", "\""); // escape quote        
        }
    }
}