package com.paras.model;

import java.util.UUID;

public class TObjectconstraint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_objectconstraint.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer object_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_objectconstraint.Constraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String constraint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_objectconstraint.ConstraintType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String constraintType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_objectconstraint.Weight
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_objectconstraint.Status
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_objectconstraint.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String notes;
    
    public TObjectconstraint() {
        
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_objectconstraint.Object_ID
     *
     * @return the value of t_objectconstraint.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getObject_ID() {
        return object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_objectconstraint.Object_ID
     *
     * @param object_ID the value for t_objectconstraint.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setObject_ID(Integer object_ID) {
        this.object_ID = object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_objectconstraint.Constraint
     *
     * @return the value of t_objectconstraint.Constraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getConstraint() {
        return constraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_objectconstraint.Constraint
     *
     * @param constraint the value for t_objectconstraint.Constraint
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setConstraint(String constraint) {
        this.constraint = constraint == null ? null : constraint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_objectconstraint.ConstraintType
     *
     * @return the value of t_objectconstraint.ConstraintType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getConstraintType() {
        return constraintType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_objectconstraint.ConstraintType
     *
     * @param constraintType the value for t_objectconstraint.ConstraintType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setConstraintType(String constraintType) {
        this.constraintType = constraintType == null ? null : constraintType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_objectconstraint.Weight
     *
     * @return the value of t_objectconstraint.Weight
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_objectconstraint.Weight
     *
     * @param weight the value for t_objectconstraint.Weight
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_objectconstraint.Status
     *
     * @return the value of t_objectconstraint.Status
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_objectconstraint.Status
     *
     * @param status the value for t_objectconstraint.Status
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_objectconstraint.Notes
     *
     * @return the value of t_objectconstraint.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_objectconstraint.Notes
     *
     * @param notes the value for t_objectconstraint.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
        if(this.notes != null) {
            this.notes.replace("'", "\'"); // escape quote
            this.notes.replace("", "\""); // escape quote        
        }
    }
    
    public void appendNotes(String notes) {
        StringBuilder sb = new StringBuilder(this.notes);
        sb.append("\n");
        sb.append("-------------");
        sb.append(notes == null ? null : notes.trim());
        this.notes = sb.toString();
    }
}