package com.paras.model;

import java.util.Date;
import java.util.UUID;

public class TObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer object_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Object_Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String object_Type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Diagram_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer diagram_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Alias
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Author
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Version
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Package_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer package_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Stereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String stereotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.NType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer NType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Complexity
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String complexity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Effort
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer effort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Style
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Backcolor
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer backcolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.BorderStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer borderStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.BorderWidth
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer borderWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Fontcolor
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer fontcolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Bordercolor
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer bordercolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.CreatedDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.ModifiedDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Status
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Abstract
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String abstractness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Tagged
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer tagged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.PDATA1
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String PDATA1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.PDATA2
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String PDATA2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.PDATA3
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String PDATA3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.PDATA4
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String PDATA4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.PDATA5
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String PDATA5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Concurrency
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String concurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Visibility
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String visibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Persistence
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String persistence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Cardinality
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String cardinality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.GenType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String genType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.GenFile
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String genFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Phase
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String phase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Scope
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Classifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer classifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String ea_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.ParentID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer parentID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Classifier_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String classifier_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.TPos
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer TPos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.IsRoot
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean isRoot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.IsLeaf
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.IsSpec
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean isSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.IsActive
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.StateFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String stateFlags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.PackageFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String packageFlags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Multiplicity
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String multiplicity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.ActionFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String actionFlags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.EventFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String eventFlags;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.GenLinks
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String genLinks;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.GenOption
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String genOption;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Header1
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String header1;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Header2
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String header2;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.Note
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String note;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.RunState
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String runState;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_object.StyleEx
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String styleEx;
    
    public TObject() {
        this(false);
    }
    
    public TObject(boolean init) {
        if(init) {
            setObject_Type("Class");
            setEa_guid("{" + UUID.randomUUID() + "}");        
        } 
    }
    
    public void initGuid() {
        setEa_guid("{" + UUID.randomUUID() + "}");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Object_ID
     *
     * @return the value of t_object.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getObject_ID() {
        return object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Object_ID
     *
     * @param object_ID the value for t_object.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setObject_ID(Integer object_ID) {
        this.object_ID = object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Object_Type
     *
     * @return the value of t_object.Object_Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getObject_Type() {
        return object_Type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Object_Type
     *
     * @param object_Type the value for t_object.Object_Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public final void setObject_Type(String object_Type) {
        this.object_Type = object_Type == null ? null : object_Type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Diagram_ID
     *
     * @return the value of t_object.Diagram_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getDiagram_ID() {
        return diagram_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Diagram_ID
     *
     * @param diagram_ID the value for t_object.Diagram_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDiagram_ID(Integer diagram_ID) {
        this.diagram_ID = diagram_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Name
     *
     * @return the value of t_object.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Name
     *
     * @param name the value for t_object.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Alias
     *
     * @return the value of t_object.Alias
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Alias
     *
     * @param alias the value for t_object.Alias
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Author
     *
     * @return the value of t_object.Author
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Author
     *
     * @param author the value for t_object.Author
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Version
     *
     * @return the value of t_object.Version
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Version
     *
     * @param version the value for t_object.Version
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Package_ID
     *
     * @return the value of t_object.Package_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getPackage_ID() {
        return package_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Package_ID
     *
     * @param package_ID the value for t_object.Package_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPackage_ID(Integer package_ID) {
        this.package_ID = package_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Stereotype
     *
     * @return the value of t_object.Stereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getStereotype() {
        return stereotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Stereotype
     *
     * @param stereotype the value for t_object.Stereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStereotype(String stereotype) {
        this.stereotype = stereotype == null ? null : stereotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.NType
     *
     * @return the value of t_object.NType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getNType() {
        return NType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.NType
     *
     * @param NType the value for t_object.NType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setNType(Integer NType) {
        this.NType = NType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Complexity
     *
     * @return the value of t_object.Complexity
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getComplexity() {
        return complexity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Complexity
     *
     * @param complexity the value for t_object.Complexity
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setComplexity(String complexity) {
        this.complexity = complexity == null ? null : complexity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Effort
     *
     * @return the value of t_object.Effort
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getEffort() {
        return effort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Effort
     *
     * @param effort the value for t_object.Effort
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setEffort(Integer effort) {
        this.effort = effort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Style
     *
     * @return the value of t_object.Style
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Style
     *
     * @param style the value for t_object.Style
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Backcolor
     *
     * @return the value of t_object.Backcolor
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getBackcolor() {
        return backcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Backcolor
     *
     * @param backcolor the value for t_object.Backcolor
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setBackcolor(Integer backcolor) {
        this.backcolor = backcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.BorderStyle
     *
     * @return the value of t_object.BorderStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getBorderStyle() {
        return borderStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.BorderStyle
     *
     * @param borderStyle the value for t_object.BorderStyle
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setBorderStyle(Integer borderStyle) {
        this.borderStyle = borderStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.BorderWidth
     *
     * @return the value of t_object.BorderWidth
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getBorderWidth() {
        return borderWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.BorderWidth
     *
     * @param borderWidth the value for t_object.BorderWidth
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setBorderWidth(Integer borderWidth) {
        this.borderWidth = borderWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Fontcolor
     *
     * @return the value of t_object.Fontcolor
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getFontcolor() {
        return fontcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Fontcolor
     *
     * @param fontcolor the value for t_object.Fontcolor
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setFontcolor(Integer fontcolor) {
        this.fontcolor = fontcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Bordercolor
     *
     * @return the value of t_object.Bordercolor
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getBordercolor() {
        return bordercolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Bordercolor
     *
     * @param bordercolor the value for t_object.Bordercolor
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setBordercolor(Integer bordercolor) {
        this.bordercolor = bordercolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.CreatedDate
     *
     * @return the value of t_object.CreatedDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.CreatedDate
     *
     * @param createdDate the value for t_object.CreatedDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.ModifiedDate
     *
     * @return the value of t_object.ModifiedDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.ModifiedDate
     *
     * @param modifiedDate the value for t_object.ModifiedDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Status
     *
     * @return the value of t_object.Status
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Status
     *
     * @param status the value for t_object.Status
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Abstract
     *
     * @return the value of t_object.Abstract
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getAbstractness() {
        return abstractness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Abstract
     *
     * @param abstractness the value for t_object.Abstract
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setAbstractness(String abstractness) {
        this.abstractness = abstractness == null ? null : abstractness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Tagged
     *
     * @return the value of t_object.Tagged
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getTagged() {
        return tagged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Tagged
     *
     * @param tagged the value for t_object.Tagged
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setTagged(Integer tagged) {
        this.tagged = tagged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.PDATA1
     *
     * @return the value of t_object.PDATA1
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPDATA1() {
        return PDATA1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.PDATA1
     *
     * @param PDATA1 the value for t_object.PDATA1
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPDATA1(String PDATA1) {
        this.PDATA1 = PDATA1 == null ? null : PDATA1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.PDATA2
     *
     * @return the value of t_object.PDATA2
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPDATA2() {
        return PDATA2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.PDATA2
     *
     * @param PDATA2 the value for t_object.PDATA2
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPDATA2(String PDATA2) {
        this.PDATA2 = PDATA2 == null ? null : PDATA2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.PDATA3
     *
     * @return the value of t_object.PDATA3
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPDATA3() {
        return PDATA3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.PDATA3
     *
     * @param PDATA3 the value for t_object.PDATA3
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPDATA3(String PDATA3) {
        this.PDATA3 = PDATA3 == null ? null : PDATA3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.PDATA4
     *
     * @return the value of t_object.PDATA4
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPDATA4() {
        return PDATA4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.PDATA4
     *
     * @param PDATA4 the value for t_object.PDATA4
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPDATA4(String PDATA4) {
        this.PDATA4 = PDATA4 == null ? null : PDATA4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.PDATA5
     *
     * @return the value of t_object.PDATA5
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPDATA5() {
        return PDATA5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.PDATA5
     *
     * @param PDATA5 the value for t_object.PDATA5
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPDATA5(String PDATA5) {
        this.PDATA5 = PDATA5 == null ? null : PDATA5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Concurrency
     *
     * @return the value of t_object.Concurrency
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getConcurrency() {
        return concurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Concurrency
     *
     * @param concurrency the value for t_object.Concurrency
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setConcurrency(String concurrency) {
        this.concurrency = concurrency == null ? null : concurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Visibility
     *
     * @return the value of t_object.Visibility
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getVisibility() {
        return visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Visibility
     *
     * @param visibility the value for t_object.Visibility
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setVisibility(String visibility) {
        this.visibility = visibility == null ? null : visibility.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Persistence
     *
     * @return the value of t_object.Persistence
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPersistence() {
        return persistence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Persistence
     *
     * @param persistence the value for t_object.Persistence
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPersistence(String persistence) {
        this.persistence = persistence == null ? null : persistence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Cardinality
     *
     * @return the value of t_object.Cardinality
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getCardinality() {
        return cardinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Cardinality
     *
     * @param cardinality the value for t_object.Cardinality
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setCardinality(String cardinality) {
        this.cardinality = cardinality == null ? null : cardinality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.GenType
     *
     * @return the value of t_object.GenType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getGenType() {
        return genType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.GenType
     *
     * @param genType the value for t_object.GenType
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setGenType(String genType) {
        this.genType = genType == null ? null : genType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.GenFile
     *
     * @return the value of t_object.GenFile
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getGenFile() {
        return genFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.GenFile
     *
     * @param genFile the value for t_object.GenFile
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setGenFile(String genFile) {
        this.genFile = genFile == null ? null : genFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Phase
     *
     * @return the value of t_object.Phase
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPhase() {
        return phase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Phase
     *
     * @param phase the value for t_object.Phase
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPhase(String phase) {
        this.phase = phase == null ? null : phase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Scope
     *
     * @return the value of t_object.Scope
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Scope
     *
     * @param scope the value for t_object.Scope
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Classifier
     *
     * @return the value of t_object.Classifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getClassifier() {
        return classifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Classifier
     *
     * @param classifier the value for t_object.Classifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setClassifier(Integer classifier) {
        this.classifier = classifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.ea_guid
     *
     * @return the value of t_object.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getEa_guid() {
        return ea_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.ea_guid
     *
     * @param ea_guid the value for t_object.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public final void setEa_guid(String ea_guid) {
        this.ea_guid = ea_guid == null ? null : ea_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.ParentID
     *
     * @return the value of t_object.ParentID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getParentID() {
        return parentID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.ParentID
     *
     * @param parentID the value for t_object.ParentID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setParentID(Integer parentID) {
        this.parentID = parentID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Classifier_guid
     *
     * @return the value of t_object.Classifier_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getClassifier_guid() {
        return classifier_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Classifier_guid
     *
     * @param classifier_guid the value for t_object.Classifier_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setClassifier_guid(String classifier_guid) {
        this.classifier_guid = classifier_guid == null ? null : classifier_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.TPos
     *
     * @return the value of t_object.TPos
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getTPos() {
        return TPos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.TPos
     *
     * @param TPos the value for t_object.TPos
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setTPos(Integer TPos) {
        this.TPos = TPos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.IsRoot
     *
     * @return the value of t_object.IsRoot
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getIsRoot() {
        return isRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.IsRoot
     *
     * @param isRoot the value for t_object.IsRoot
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsRoot(Boolean isRoot) {
        this.isRoot = isRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.IsLeaf
     *
     * @return the value of t_object.IsLeaf
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.IsLeaf
     *
     * @param isLeaf the value for t_object.IsLeaf
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsLeaf(Boolean isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.IsSpec
     *
     * @return the value of t_object.IsSpec
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getIsSpec() {
        return isSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.IsSpec
     *
     * @param isSpec the value for t_object.IsSpec
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsSpec(Boolean isSpec) {
        this.isSpec = isSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.IsActive
     *
     * @return the value of t_object.IsActive
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.IsActive
     *
     * @param isActive the value for t_object.IsActive
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.StateFlags
     *
     * @return the value of t_object.StateFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getStateFlags() {
        return stateFlags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.StateFlags
     *
     * @param stateFlags the value for t_object.StateFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStateFlags(String stateFlags) {
        this.stateFlags = stateFlags == null ? null : stateFlags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.PackageFlags
     *
     * @return the value of t_object.PackageFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPackageFlags() {
        return packageFlags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.PackageFlags
     *
     * @param packageFlags the value for t_object.PackageFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPackageFlags(String packageFlags) {
        this.packageFlags = packageFlags == null ? null : packageFlags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Multiplicity
     *
     * @return the value of t_object.Multiplicity
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getMultiplicity() {
        return multiplicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Multiplicity
     *
     * @param multiplicity the value for t_object.Multiplicity
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setMultiplicity(String multiplicity) {
        this.multiplicity = multiplicity == null ? null : multiplicity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.ActionFlags
     *
     * @return the value of t_object.ActionFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getActionFlags() {
        return actionFlags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.ActionFlags
     *
     * @param actionFlags the value for t_object.ActionFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setActionFlags(String actionFlags) {
        this.actionFlags = actionFlags == null ? null : actionFlags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.EventFlags
     *
     * @return the value of t_object.EventFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getEventFlags() {
        return eventFlags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.EventFlags
     *
     * @param eventFlags the value for t_object.EventFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setEventFlags(String eventFlags) {
        this.eventFlags = eventFlags == null ? null : eventFlags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.GenLinks
     *
     * @return the value of t_object.GenLinks
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getGenLinks() {
        return genLinks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.GenOption
     *
     * @return the value of t_object.GenOption
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getGenOption() {
        return genOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Header1
     *
     * @return the value of t_object.Header1
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getHeader1() {
        return header1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Header2
     *
     * @return the value of t_object.Header2
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getHeader2() {
        return header2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.Note
     *
     * @return the value of t_object.Note
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.RunState
     *
     * @return the value of t_object.RunState
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getRunState() {
        return runState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_object.StyleEx
     *
     * @return the value of t_object.StyleEx
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getStyleEx() {
        return styleEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.GenLinks
     *
     * @param genLinks the value for t_object.GenLinks
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setGenLinks(String genLinks) {
        this.genLinks = genLinks == null ? null : genLinks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.GenOption
     *
     * @param genOption the value for t_object.GenOption
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setGenOption(String genOption) {
        this.genOption = genOption == null ? null : genOption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Header1
     *
     * @param header1 the value for t_object.Header1
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setHeader1(String header1) {
        this.header1 = header1 == null ? null : header1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Header2
     *
     * @param header2 the value for t_object.Header2
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setHeader2(String header2) {
        this.header2 = header2 == null ? null : header2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.Note
     *
     * @param note the value for t_object.Note
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
        if(this.note != null) {
            this.note.replace("'", "\'"); // escape quote
            this.note.replace("", "\""); // escape quote
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.RunState
     *
     * @param runState the value for t_object.RunState
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setRunState(String runState) {
        this.runState = runState == null ? null : runState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_object.StyleEx
     *
     * @param styleEx the value for t_object.StyleEx
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStyleEx(String styleEx) {
        this.styleEx = styleEx == null ? null : styleEx.trim();
    }
    
     @Override
    public boolean equals(Object obj) {
        if(! (obj instanceof TObject)) {
            return false;
        }
        TObject object = (TObject) obj;
        return getEa_guid().equals(object.getEa_guid());
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + (this.ea_guid != null ? this.ea_guid.hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "TObject{" + "object_ID=" + object_ID + ", object_Type=" + object_Type + ", diagram_ID=" + diagram_ID + ", name=" + name + ", alias=" + alias + ", author=" + author + ", version=" + version + ", package_ID=" + package_ID + ", stereotype=" + stereotype + ", NType=" + NType + ", complexity=" + complexity + ", effort=" + effort + ", style=" + style + ", backcolor=" + backcolor + ", borderStyle=" + borderStyle + ", borderWidth=" + borderWidth + ", fontcolor=" + fontcolor + ", bordercolor=" + bordercolor + ", createdDate=" + createdDate + ", modifiedDate=" + modifiedDate + ", status=" + status + ", abstractness=" + abstractness + ", tagged=" + tagged + ", PDATA1=" + PDATA1 + ", PDATA2=" + PDATA2 + ", PDATA3=" + PDATA3 + ", PDATA4=" + PDATA4 + ", PDATA5=" + PDATA5 + ", concurrency=" + concurrency + ", visibility=" + visibility + ", persistence=" + persistence + ", cardinality=" + cardinality + ", genType=" + genType + ", genFile=" + genFile + ", phase=" + phase + ", scope=" + scope + ", classifier=" + classifier + ", ea_guid=" + ea_guid + ", parentID=" + parentID + ", classifier_guid=" + classifier_guid + ", TPos=" + TPos + ", isRoot=" + isRoot + ", isLeaf=" + isLeaf + ", isSpec=" + isSpec + ", isActive=" + isActive + ", stateFlags=" + stateFlags + ", packageFlags=" + packageFlags + ", multiplicity=" + multiplicity + ", actionFlags=" + actionFlags + ", eventFlags=" + eventFlags + ", genLinks=" + genLinks + ", genOption=" + genOption + ", header1=" + header1 + ", header2=" + header2 + ", note=" + note + ", runState=" + runState + ", styleEx=" + styleEx + '}';
    }
    
}