package com.paras.model;

public class TOperationparams {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operationparams.OperationID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer operationID;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operationparams.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operationparams.Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String type;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operationparams.Default
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String defaultVal;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operationparams.Pos
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer pos;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operationparams.Const
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean constant;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operationparams.Style
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String style;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operationparams.Kind
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String kind;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operationparams.Classifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String classifier;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operationparams.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String ea_guid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operationparams.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String notes;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operationparams.StyleEx
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    protected String styleEx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operationparams.OperationID
     *
     * @return the value of t_operationparams.OperationID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getOperationID() {
        return operationID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operationparams.OperationID
     *
     * @param operationID the value for t_operationparams.OperationID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setOperationID(Integer operationID) {
        this.operationID = operationID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operationparams.Name
     *
     * @return the value of t_operationparams.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operationparams.Name
     *
     * @param name the value for t_operationparams.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operationparams.Type
     *
     * @return the value of t_operationparams.Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operationparams.Type
     *
     * @param type the value for t_operationparams.Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operationparams.Default
     *
     * @return the value of t_operationparams.Default
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getDefaultVal() {
        return defaultVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operationparams.Default
     *
     * @param defaultVal the value for t_operationparams.Default
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setDefaultVal(String defaultVal) {
        this.defaultVal = defaultVal == null ? null : defaultVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operationparams.Pos
     *
     * @return the value of t_operationparams.Pos
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operationparams.Pos
     *
     * @param pos the value for t_operationparams.Pos
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPos(Integer pos) {
        this.pos = pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operationparams.Const
     *
     * @return the value of t_operationparams.Const
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getConstant() {
        return constant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operationparams.Const
     *
     * @param constant the value for t_operationparams.Const
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setConstant(Boolean constant) {
        this.constant = constant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operationparams.Style
     *
     * @return the value of t_operationparams.Style
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operationparams.Style
     *
     * @param style the value for t_operationparams.Style
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operationparams.Kind
     *
     * @return the value of t_operationparams.Kind
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operationparams.Kind
     *
     * @param kind the value for t_operationparams.Kind
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operationparams.Classifier
     *
     * @return the value of t_operationparams.Classifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getClassifier() {
        return classifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operationparams.Classifier
     *
     * @param classifier the value for t_operationparams.Classifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setClassifier(String classifier) {
        this.classifier = classifier == null ? null : classifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operationparams.ea_guid
     *
     * @return the value of t_operationparams.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getEa_guid() {
        return ea_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operationparams.ea_guid
     *
     * @param ea_guid the value for t_operationparams.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setEa_guid(String ea_guid) {
        this.ea_guid = ea_guid == null ? null : ea_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operationparams.Notes
     *
     * @return the value of t_operationparams.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operationparams.StyleEx
     *
     * @return the value of t_operationparams.StyleEx
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getStyleEx() {
        return styleEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operationparams.Notes
     *
     * @param notes the value for t_operationparams.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
        if (this.notes != null) {
            this.notes.replace("'", "\'"); // escape quote
            this.notes.replace("", "\""); // escape quote
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operationparams.StyleEx
     *
     * @param styleEx the value for t_operationparams.StyleEx
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStyleEx(String styleEx) {
        this.styleEx = styleEx == null ? null : styleEx.trim();
    }
}