package com.paras.model;

public class TOperation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.OperationID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer operationID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer object_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.Scope
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.ReturnArray
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String returnArray;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.Stereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String stereotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.IsStatic
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String isStatic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.Concurrency
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String concurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.Abstract
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String abstractness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.Synchronized
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String synchronization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.Pos
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer pos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.Const
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer constant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.Style
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.Pure
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean pure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.Throws
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String throwsException;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.Classifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String classifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.IsRoot
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean isRoot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.IsLeaf
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.IsQuery
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean isQuery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.StateFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String stateFlags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String ea_guid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.OperationID
     *
     * @return the value of t_operation.OperationID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getOperationID() {
        return operationID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.OperationID
     *
     * @param operationID the value for t_operation.OperationID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setOperationID(Integer operationID) {
        this.operationID = operationID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.Object_ID
     *
     * @return the value of t_operation.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getObject_ID() {
        return object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.Object_ID
     *
     * @param object_ID the value for t_operation.Object_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setObject_ID(Integer object_ID) {
        this.object_ID = object_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.Name
     *
     * @return the value of t_operation.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.Name
     *
     * @param name the value for t_operation.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.Scope
     *
     * @return the value of t_operation.Scope
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.Scope
     *
     * @param scope the value for t_operation.Scope
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.Type
     *
     * @return the value of t_operation.Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.Type
     *
     * @param type the value for t_operation.Type
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.ReturnArray
     *
     * @return the value of t_operation.ReturnArray
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getReturnArray() {
        return returnArray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.ReturnArray
     *
     * @param returnArray the value for t_operation.ReturnArray
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setReturnArray(String returnArray) {
        this.returnArray = returnArray == null ? null : returnArray.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.Stereotype
     *
     * @return the value of t_operation.Stereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getStereotype() {
        return stereotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.Stereotype
     *
     * @param stereotype the value for t_operation.Stereotype
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStereotype(String stereotype) {
        this.stereotype = stereotype == null ? null : stereotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.IsStatic
     *
     * @return the value of t_operation.IsStatic
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getIsStatic() {
        return isStatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.IsStatic
     *
     * @param isStatic the value for t_operation.IsStatic
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsStatic(String isStatic) {
        this.isStatic = isStatic == null ? null : isStatic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.Concurrency
     *
     * @return the value of t_operation.Concurrency
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getConcurrency() {
        return concurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.Concurrency
     *
     * @param concurrency the value for t_operation.Concurrency
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setConcurrency(String concurrency) {
        this.concurrency = concurrency == null ? null : concurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.Abstract
     *
     * @return the value of t_operation.Abstract
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getAbstractness() {
        return abstractness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.Abstract
     *
     * @param abstractness the value for t_operation.Abstract
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setAbstractness(String abstractness) {
        this.abstractness = abstractness == null ? null : abstractness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.Synchronized
     *
     * @return the value of t_operation.Synchronized
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getSynchronization() {
        return synchronization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.Synchronized
     *
     * @param synchronization the value for t_operation.Synchronized
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setSynchronization(String synchronization) {
        this.synchronization = synchronization == null ? null : synchronization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.Pos
     *
     * @return the value of t_operation.Pos
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.Pos
     *
     * @param pos the value for t_operation.Pos
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPos(Integer pos) {
        this.pos = pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.Const
     *
     * @return the value of t_operation.Const
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getConstant() {
        return constant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.Const
     *
     * @param constant the value for t_operation.Const
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setConstant(Integer constant) {
        this.constant = constant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.Style
     *
     * @return the value of t_operation.Style
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.Style
     *
     * @param style the value for t_operation.Style
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.Pure
     *
     * @return the value of t_operation.Pure
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getPure() {
        return pure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.Pure
     *
     * @param pure the value for t_operation.Pure
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPure(Boolean pure) {
        this.pure = pure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.Throws
     *
     * @return the value of t_operation.Throws
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getThrowsException() {
        return throwsException;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.Throws
     *
     * @param throwsException the value for t_operation.Throws
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setThrowsException(String throwsException) {
        this.throwsException = throwsException == null ? null : throwsException.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.Classifier
     *
     * @return the value of t_operation.Classifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getClassifier() {
        return classifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.Classifier
     *
     * @param classifier the value for t_operation.Classifier
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setClassifier(String classifier) {
        this.classifier = classifier == null ? null : classifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.IsRoot
     *
     * @return the value of t_operation.IsRoot
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getIsRoot() {
        return isRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.IsRoot
     *
     * @param isRoot the value for t_operation.IsRoot
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsRoot(Boolean isRoot) {
        this.isRoot = isRoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.IsLeaf
     *
     * @return the value of t_operation.IsLeaf
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.IsLeaf
     *
     * @param isLeaf the value for t_operation.IsLeaf
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsLeaf(Boolean isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.IsQuery
     *
     * @return the value of t_operation.IsQuery
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getIsQuery() {
        return isQuery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.IsQuery
     *
     * @param isQuery the value for t_operation.IsQuery
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsQuery(Boolean isQuery) {
        this.isQuery = isQuery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.StateFlags
     *
     * @return the value of t_operation.StateFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getStateFlags() {
        return stateFlags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.StateFlags
     *
     * @param stateFlags the value for t_operation.StateFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setStateFlags(String stateFlags) {
        this.stateFlags = stateFlags == null ? null : stateFlags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.ea_guid
     *
     * @return the value of t_operation.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getEa_guid() {
        return ea_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.ea_guid
     *
     * @param ea_guid the value for t_operation.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setEa_guid(String ea_guid) {
        this.ea_guid = ea_guid == null ? null : ea_guid.trim();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TOperation other = (TOperation) obj;
        if ((this.ea_guid == null) ? (other.ea_guid != null) : !this.ea_guid.equals(other.ea_guid)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + (this.ea_guid != null ? this.ea_guid.hashCode() : 0);
        return hash;
    }
}