package com.paras.model;

import java.util.Date;

public class TPackage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.Package_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer package_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.Parent_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer parent_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.CreatedDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.ModifiedDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String ea_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.XMLPath
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String XMLPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.IsControlled
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean isControlled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.LastLoadDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Date lastLoadDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.LastSaveDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Date lastSaveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.Version
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.Protected
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean protect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.PkgOwner
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String pkgOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.UMLVersion
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String UMLVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.UseDTD
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean useDTD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.LogXML
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Boolean logXML;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.CodePath
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String codePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.Namespace
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String namespace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.TPos
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer TPos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.PackageFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String packageFlags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.BatchSave
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer batchSave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.BatchLoad
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private Integer batchLoad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.Package_ID
     *
     * @return the value of t_package.Package_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getPackage_ID() {
        return package_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.Package_ID
     *
     * @param package_ID the value for t_package.Package_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPackage_ID(Integer package_ID) {
        this.package_ID = package_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.Name
     *
     * @return the value of t_package.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.Name
     *
     * @param name the value for t_package.Name
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.Parent_ID
     *
     * @return the value of t_package.Parent_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getParent_ID() {
        return parent_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.Parent_ID
     *
     * @param parent_ID the value for t_package.Parent_ID
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setParent_ID(Integer parent_ID) {
        this.parent_ID = parent_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.CreatedDate
     *
     * @return the value of t_package.CreatedDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.CreatedDate
     *
     * @param createdDate the value for t_package.CreatedDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.ModifiedDate
     *
     * @return the value of t_package.ModifiedDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.ModifiedDate
     *
     * @param modifiedDate the value for t_package.ModifiedDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.ea_guid
     *
     * @return the value of t_package.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getEa_guid() {
        return ea_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.ea_guid
     *
     * @param ea_guid the value for t_package.ea_guid
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setEa_guid(String ea_guid) {
        this.ea_guid = ea_guid == null ? null : ea_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.XMLPath
     *
     * @return the value of t_package.XMLPath
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getXMLPath() {
        return XMLPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.XMLPath
     *
     * @param XMLPath the value for t_package.XMLPath
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setXMLPath(String XMLPath) {
        this.XMLPath = XMLPath == null ? null : XMLPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.IsControlled
     *
     * @return the value of t_package.IsControlled
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getIsControlled() {
        return isControlled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.IsControlled
     *
     * @param isControlled the value for t_package.IsControlled
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setIsControlled(Boolean isControlled) {
        this.isControlled = isControlled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.LastLoadDate
     *
     * @return the value of t_package.LastLoadDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Date getLastLoadDate() {
        return lastLoadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.LastLoadDate
     *
     * @param lastLoadDate the value for t_package.LastLoadDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setLastLoadDate(Date lastLoadDate) {
        this.lastLoadDate = lastLoadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.LastSaveDate
     *
     * @return the value of t_package.LastSaveDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Date getLastSaveDate() {
        return lastSaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.LastSaveDate
     *
     * @param lastSaveDate the value for t_package.LastSaveDate
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setLastSaveDate(Date lastSaveDate) {
        this.lastSaveDate = lastSaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.Version
     *
     * @return the value of t_package.Version
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.Version
     *
     * @param version the value for t_package.Version
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.Protected
     *
     * @return the value of t_package.Protected
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getProtect() {
        return protect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.Protected
     *
     * @param protect the value for t_package.Protected
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setProtect(Boolean protect) {
        this.protect = protect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.PkgOwner
     *
     * @return the value of t_package.PkgOwner
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPkgOwner() {
        return pkgOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.PkgOwner
     *
     * @param pkgOwner the value for t_package.PkgOwner
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPkgOwner(String pkgOwner) {
        this.pkgOwner = pkgOwner == null ? null : pkgOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.UMLVersion
     *
     * @return the value of t_package.UMLVersion
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getUMLVersion() {
        return UMLVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.UMLVersion
     *
     * @param UMLVersion the value for t_package.UMLVersion
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setUMLVersion(String UMLVersion) {
        this.UMLVersion = UMLVersion == null ? null : UMLVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.UseDTD
     *
     * @return the value of t_package.UseDTD
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getUseDTD() {
        return useDTD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.UseDTD
     *
     * @param useDTD the value for t_package.UseDTD
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setUseDTD(Boolean useDTD) {
        this.useDTD = useDTD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.LogXML
     *
     * @return the value of t_package.LogXML
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Boolean getLogXML() {
        return logXML;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.LogXML
     *
     * @param logXML the value for t_package.LogXML
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setLogXML(Boolean logXML) {
        this.logXML = logXML;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.CodePath
     *
     * @return the value of t_package.CodePath
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getCodePath() {
        return codePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.CodePath
     *
     * @param codePath the value for t_package.CodePath
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setCodePath(String codePath) {
        this.codePath = codePath == null ? null : codePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.Namespace
     *
     * @return the value of t_package.Namespace
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.Namespace
     *
     * @param namespace the value for t_package.Namespace
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setNamespace(String namespace) {
        this.namespace = namespace == null ? null : namespace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.TPos
     *
     * @return the value of t_package.TPos
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getTPos() {
        return TPos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.TPos
     *
     * @param TPos the value for t_package.TPos
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setTPos(Integer TPos) {
        this.TPos = TPos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.PackageFlags
     *
     * @return the value of t_package.PackageFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getPackageFlags() {
        return packageFlags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.PackageFlags
     *
     * @param packageFlags the value for t_package.PackageFlags
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setPackageFlags(String packageFlags) {
        this.packageFlags = packageFlags == null ? null : packageFlags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.BatchSave
     *
     * @return the value of t_package.BatchSave
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getBatchSave() {
        return batchSave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.BatchSave
     *
     * @param batchSave the value for t_package.BatchSave
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setBatchSave(Integer batchSave) {
        this.batchSave = batchSave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.BatchLoad
     *
     * @return the value of t_package.BatchLoad
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public Integer getBatchLoad() {
        return batchLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.BatchLoad
     *
     * @param batchLoad the value for t_package.BatchLoad
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setBatchLoad(Integer batchLoad) {
        this.batchLoad = batchLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.Notes
     *
     * @return the value of t_package.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.Notes
     *
     * @param notes the value for t_package.Notes
     *
     * @mbggenerated Thu Feb 16 09:50:26 NZDT 2012
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
        if(this.notes != null) {
            this.notes.replace("'", "\'"); // escape quote
            this.notes.replace("", "\""); // escape quote            
        }
    }
    
    @Override
    public boolean equals(Object obj) {
        if(! (obj instanceof TPackage)) {
            return false;
        }
        TPackage pkg = (TPackage) obj;
        return getEa_guid().equals(pkg.getEa_guid());
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 37 * hash + (this.ea_guid != null ? this.ea_guid.hashCode() : 0);
        return hash;
    }
}